export const data = [
  {
    date: "20-10-2021",
    location: "Forest Dale",
    remarks: "reintermediate proactive platforms",
    materialName: "Stone",
    quantity: 11,
    unit: "ST",
  },
  {
    date: "06-06-2022",
    location: "Merchant",
    remarks: "envisioneer efficient relationships",
    materialName: "Plexiglass",
    quantity: 57,
    unit: "L",
  },
  {
    date: "08-04-2022",
    location: "Loomis",
    remarks: "engage impactful portals",
    materialName: "Aluminum",
    quantity: 50,
    unit: "ST",
  },
  {
    date: "14-02-2022",
    location: "Summer Ridge",
    remarks: "incubate plug-and-play web services",
    materialName: "Wood",
    quantity: 72,
    unit: "L",
  },
  {
    date: "21-10-2021",
    location: "Crownhardt",
    remarks: "iterate holistic mindshare",
    materialName: "Glass",
    quantity: 2,
    unit: "ST",
  },
  {
    date: "28-12-2021",
    location: "Derek",
    remarks: "engineer web-enabled solutions",
    materialName: "Plexiglass",
    quantity: 62,
    unit: "L",
  },
  {
    date: "24-10-2021",
    location: "Farwell",
    remarks: "enhance one-to-one portals",
    materialName: "Granite",
    quantity: 65,
    unit: "ST",
  },
  {
    date: "01-05-2022",
    location: "Badeau",
    remarks: "disintermediate granular markets",
    materialName: "Stone",
    quantity: 84,
    unit: "ROL",
  },
  {
    date: "24-01-2022",
    location: "Bartelt",
    remarks: "mesh distributed infrastructures",
    materialName: "Stone",
    quantity: 67,
    unit: "ROL",
  },
  {
    date: "23-07-2022",
    location: "Rowland",
    remarks: "syndicate e-business web services",
    materialName: "Rubber",
    quantity: 37,
    unit: "ST",
  },
  {
    date: "11-03-2022",
    location: "Onsgard",
    remarks: "extend seamless solutions",
    materialName: "Vinyl",
    quantity: 82,
    unit: "ST",
  },
  {
    date: "16-09-2021",
    location: "Surrey",
    remarks: "deploy 24/7 e-commerce",
    materialName: "Brass",
    quantity: 42,
    unit: "KG",
  },
  {
    date: "26-09-2021",
    location: "Petterle",
    remarks: "syndicate scalable synergies",
    materialName: "Vinyl",
    quantity: 78,
    unit: "L",
  },
  {
    date: "01-07-2022",
    location: "Dovetail",
    remarks: "iterate vertical methodologies",
    materialName: "Steel",
    quantity: 86,
    unit: "ROL",
  },
  {
    date: "29-09-2021",
    location: "Vera",
    remarks: "empower proactive e-markets",
    materialName: "Granite",
    quantity: 40,
    unit: "ST",
  },
  {
    date: "01-01-2022",
    location: "Sunbrook",
    remarks: "incubate wireless paradigms",
    materialName: "Aluminum",
    quantity: 66,
    unit: "L",
  },
  {
    date: "26-10-2021",
    location: "Forest",
    remarks: "drive mission-critical methodologies",
    materialName: "Granite",
    quantity: 70,
    unit: "ST",
  },
  {
    date: "11-11-2021",
    location: "Harbort",
    remarks: "engage front-end e-markets",
    materialName: "Plastic",
    quantity: 50,
    unit: "ST",
  },
  {
    date: "30-01-2022",
    location: "Dwight",
    remarks: "redefine bleeding-edge communities",
    materialName: "Plexiglass",
    quantity: 19,
    unit: "L",
  },
  {
    date: "07-04-2022",
    location: "Anniversary",
    remarks: "productize distributed partnerships",
    materialName: "Vinyl",
    quantity: 48,
    unit: "L",
  },
  {
    date: "20-01-2022",
    location: "Bunker Hill",
    remarks: "implement cross-media experiences",
    materialName: "Granite",
    quantity: 59,
    unit: "KG",
  },
  {
    date: "13-09-2021",
    location: "Manley",
    remarks: "target next-generation users",
    materialName: "Rubber",
    quantity: 13,
    unit: "L",
  },
  {
    date: "01-05-2022",
    location: "Anderson",
    remarks: "reinvent world-class portals",
    materialName: "Glass",
    quantity: 19,
    unit: "L",
  },
  {
    date: "07-08-2022",
    location: "Holy Cross",
    remarks: "empower impactful markets",
    materialName: "Steel",
    quantity: 70,
    unit: "ROL",
  },
  {
    date: "15-10-2021",
    location: "Karstens",
    remarks: "deploy user-centric initiatives",
    materialName: "Wood",
    quantity: 39,
    unit: "ROL",
  },
  {
    date: "11-06-2022",
    location: "Corben",
    remarks: "benchmark best-of-breed content",
    materialName: "Vinyl",
    quantity: 50,
    unit: "L",
  },
  {
    date: "20-09-2021",
    location: "Anderson",
    remarks: "reintermediate scalable relationships",
    materialName: "Brass",
    quantity: 29,
    unit: "ST",
  },
  {
    date: "27-03-2022",
    location: "Northridge",
    remarks: "utilize scalable e-commerce",
    materialName: "Brass",
    quantity: 57,
    unit: "ST",
  },
  {
    date: "13-10-2021",
    location: "Reindahl",
    remarks: "empower cross-media communities",
    materialName: "Aluminum",
    quantity: 6,
    unit: "L",
  },
  {
    date: "19-12-2021",
    location: "Dapin",
    remarks: "recontextualize 24/365 solutions",
    materialName: "Stone",
    quantity: 39,
    unit: "ST",
  },
  {
    date: "10-12-2021",
    location: "Marquette",
    remarks: "deploy scalable web-readiness",
    materialName: "Rubber",
    quantity: 84,
    unit: "L",
  },
  {
    date: "23-01-2022",
    location: "Homewood",
    remarks: "utilize intuitive users",
    materialName: "Vinyl",
    quantity: 10,
    unit: "L",
  },
  {
    date: "30-06-2022",
    location: "Drewry",
    remarks: "incubate end-to-end communities",
    materialName: "Aluminum",
    quantity: 89,
    unit: "ST",
  },
  {
    date: "17-05-2022",
    location: "Clyde Gallagher",
    remarks: "enhance leading-edge methodologies",
    materialName: "Glass",
    quantity: 34,
    unit: "L",
  },
  {
    date: "22-04-2022",
    location: "Moland",
    remarks: "cultivate bleeding-edge e-tailers",
    materialName: "Plastic",
    quantity: 93,
    unit: "ST",
  },
  {
    date: "04-06-2022",
    location: "Armistice",
    remarks: "enhance real-time convergence",
    materialName: "Steel",
    quantity: 13,
    unit: "ST",
  },
  {
    date: "20-12-2021",
    location: "Graedel",
    remarks: "benchmark proactive supply-chains",
    materialName: "Granite",
    quantity: 15,
    unit: "L",
  },
  {
    date: "05-10-2021",
    location: "Crest Line",
    remarks: "syndicate 24/7 deliverables",
    materialName: "Stone",
    quantity: 64,
    unit: "ST",
  },
  {
    date: "19-11-2021",
    location: "Superior",
    remarks: "engineer visionary action-items",
    materialName: "Steel",
    quantity: 53,
    unit: "KG",
  },
  {
    date: "07-05-2022",
    location: "Fremont",
    remarks: "incentivize collaborative communities",
    materialName: "Rubber",
    quantity: 72,
    unit: "ST",
  },
  {
    date: "26-05-2022",
    location: "Northport",
    remarks: "utilize one-to-one technologies",
    materialName: "Stone",
    quantity: 21,
    unit: "ST",
  },
  {
    date: "11-12-2021",
    location: "Bluejay",
    remarks: "expedite innovative eyeballs",
    materialName: "Aluminum",
    quantity: 38,
    unit: "ST",
  },
  {
    date: "20-03-2022",
    location: "Butterfield",
    remarks: "cultivate one-to-one relationships",
    materialName: "Granite",
    quantity: 96,
    unit: "ST",
  },
  {
    date: "09-02-2022",
    location: "Huxley",
    remarks: "exploit impactful systems",
    materialName: "Vinyl",
    quantity: 14,
    unit: "ST",
  },
  {
    date: "02-11-2021",
    location: "Westend",
    remarks: "monetize integrated e-tailers",
    materialName: "Stone",
    quantity: 97,
    unit: "EA",
  },
  {
    date: "08-11-2021",
    location: "Schmedeman",
    remarks: "grow vertical eyeballs",
    materialName: "Stone",
    quantity: 82,
    unit: "ST",
  },
  {
    date: "17-04-2022",
    location: "Burrows",
    remarks: "morph world-class users",
    materialName: "Plexiglass",
    quantity: 43,
    unit: "ST",
  },
  {
    date: "24-06-2022",
    location: "Dennis",
    remarks: "monetize vertical partnerships",
    materialName: "Glass",
    quantity: 41,
    unit: "ST",
  },
  {
    date: "24-01-2022",
    location: "Holy Cross",
    remarks: "leverage granular users",
    materialName: "Wood",
    quantity: 94,
    unit: "ST",
  },
  {
    date: "19-04-2022",
    location: "Clove",
    remarks: "incentivize sticky communities",
    materialName: "Steel",
    quantity: 93,
    unit: "ROL",
  },
];

export const materials = [
  {
    id: 1,
    materialName: "Glass",
  },
  {
    id: 2,
    materialName: "Granite",
  },
  {
    id: 3,
    materialName: "Aluminum",
  },
  {
    id: 4,
    materialName: "Wood",
  },
  {
    id: 5,
    materialName: "Brass",
  },
  {
    id: 6,
    materialName: "Vinyl",
  },
  {
    id: 7,
    materialName: "Stone",
  },
  {
    id: 8,
    materialName: "Granite",
  },
  {
    id: 9,
    materialName: "Vinyl",
  },
  {
    id: 10,
    materialName: "Brass",
  },
  {
    id: 11,
    materialName: "Granite",
  },
  {
    id: 12,
    materialName: "Wood",
  },
  {
    id: 13,
    materialName: "Glass",
  },
  {
    id: 14,
    materialName: "Glass",
  },
  {
    id: 15,
    materialName: "Vinyl",
  },
  {
    id: 16,
    materialName: "Aluminum",
  },
  {
    id: 17,
    materialName: "Plastic",
  },
  {
    id: 18,
    materialName: "Glass",
  },
  {
    id: 19,
    materialName: "Wood",
  },
  {
    id: 20,
    materialName: "Plastic",
  },
  {
    id: 21,
    materialName: "Glass",
  },
  {
    id: 22,
    materialName: "Plexiglass",
  },
  {
    id: 23,
    materialName: "Plexiglass",
  },
  {
    id: 24,
    materialName: "Glass",
  },
  {
    id: 25,
    materialName: "Plastic",
  },
  {
    id: 26,
    materialName: "Plexiglass",
  },
  {
    id: 27,
    materialName: "Wood",
  },
  {
    id: 28,
    materialName: "Steel",
  },
  {
    id: 29,
    materialName: "Aluminum",
  },
  {
    id: 30,
    materialName: "Glass",
  },
  {
    id: 31,
    materialName: "Aluminum",
  },
  {
    id: 32,
    materialName: "Wood",
  },
  {
    id: 33,
    materialName: "Vinyl",
  },
  {
    id: 34,
    materialName: "Steel",
  },
  {
    id: 35,
    materialName: "Brass",
  },
  {
    id: 36,
    materialName: "Plexiglass",
  },
  {
    id: 37,
    materialName: "Steel",
  },
  {
    id: 38,
    materialName: "Brass",
  },
  {
    id: 39,
    materialName: "Steel",
  },
  {
    id: 40,
    materialName: "Steel",
  },
  {
    id: 41,
    materialName: "Granite",
  },
  {
    id: 42,
    materialName: "Glass",
  },
  {
    id: 43,
    materialName: "Plexiglass",
  },
  {
    id: 44,
    materialName: "Wood",
  },
  {
    id: 45,
    materialName: "Aluminum",
  },
  {
    id: 46,
    materialName: "Steel",
  },
  {
    id: 47,
    materialName: "Wood",
  },
  {
    id: 48,
    materialName: "Rubber",
  },
  {
    id: 49,
    materialName: "Stone",
  },
  {
    id: 50,
    materialName: "Steel",
  },
  {
    id: 51,
    materialName: "Vinyl",
  },
  {
    id: 52,
    materialName: "Rubber",
  },
  {
    id: 53,
    materialName: "Glass",
  },
  {
    id: 54,
    materialName: "Rubber",
  },
  {
    id: 55,
    materialName: "Vinyl",
  },
  {
    id: 56,
    materialName: "Glass",
  },
  {
    id: 57,
    materialName: "Wood",
  },
  {
    id: 58,
    materialName: "Brass",
  },
  {
    id: 59,
    materialName: "Stone",
  },
  {
    id: 60,
    materialName: "Plexiglass",
  },
  {
    id: 61,
    materialName: "Plastic",
  },
  {
    id: 62,
    materialName: "Rubber",
  },
  {
    id: 63,
    materialName: "Aluminum",
  },
  {
    id: 64,
    materialName: "Wood",
  },
  {
    id: 65,
    materialName: "Stone",
  },
  {
    id: 66,
    materialName: "Vinyl",
  },
  {
    id: 67,
    materialName: "Steel",
  },
  {
    id: 68,
    materialName: "Rubber",
  },
  {
    id: 69,
    materialName: "Granite",
  },
  {
    id: 70,
    materialName: "Granite",
  },
  {
    id: 71,
    materialName: "Brass",
  },
  {
    id: 72,
    materialName: "Granite",
  },
  {
    id: 73,
    materialName: "Stone",
  },
  {
    id: 74,
    materialName: "Aluminum",
  },
  {
    id: 75,
    materialName: "Vinyl",
  },
  {
    id: 76,
    materialName: "Plastic",
  },
  {
    id: 77,
    materialName: "Rubber",
  },
  {
    id: 78,
    materialName: "Stone",
  },
  {
    id: 79,
    materialName: "Aluminum",
  },
  {
    id: 80,
    materialName: "Vinyl",
  },
  {
    id: 81,
    materialName: "Plexiglass",
  },
  {
    id: 82,
    materialName: "Vinyl",
  },
  {
    id: 83,
    materialName: "Plastic",
  },
  {
    id: 84,
    materialName: "Granite",
  },
  {
    id: 85,
    materialName: "Rubber",
  },
  {
    id: 86,
    materialName: "Granite",
  },
  {
    id: 87,
    materialName: "Aluminum",
  },
  {
    id: 88,
    materialName: "Granite",
  },
  {
    id: 89,
    materialName: "Aluminum",
  },
  {
    id: 90,
    materialName: "Vinyl",
  },
  {
    id: 91,
    materialName: "Granite",
  },
  {
    id: 92,
    materialName: "Wood",
  },
  {
    id: 93,
    materialName: "Plexiglass",
  },
  {
    id: 94,
    materialName: "Vinyl",
  },
  {
    id: 95,
    materialName: "Vinyl",
  },
  {
    id: 96,
    materialName: "Steel",
  },
  {
    id: 97,
    materialName: "Glass",
  },
  {
    id: 98,
    materialName: "Glass",
  },
  {
    id: 99,
    materialName: "Stone",
  },
  {
    id: 100,
    materialName: "Brass",
  },
];
